Repository hee-ha/hana-heritage-FE, pull requests merged in 2024-06, with the labels that each got.

#60 로그인 및 jwt api 연결
  package-lock.json
  package.json
  src/apis/authService.js
  src/apis/axiosInstance.js
  src/context/authContext.js
  src/hooks/useAuth.js
  src/index.js
  src/pages/user/Login.jsx
  src/utils/auth.js
  src/utils/tokenService.js
Labels: ⚡️api

#81 이체내역 조회페이지 api 연결 및 refresh토큰 문제 해결
  package-lock.json
  package.json
  setupProxy.js
  src/App.jsx
  src/apis/authService.js
  src/apis/axiosInstance.js
  src/apis/transfer/TransferHistory.js
  src/components/Header.jsx
  src/context/authContext.js
  src/pages/deposits/DepositsJoin3.jsx
  src/pages/home/Home.jsx
  src/pages/transfer/SimpleTransfer.jsx
  src/pages/transfer/TransferHistory.jsx
  src/pages/transfer/component/Bankbtn.jsx
  src/pages/user/Login.jsx
  src/states/authState.js
  src/utils/auth.js
  src/utils/tokenService.js
  src/utils/utils.js
Labels: Bug🦊, 계좌, ⚡️api

#87 예적금 api 연결 및 입출금 완료
  package-lock.json
  src/apis/account/getDepositsAccountDetail.js
  src/apis/depositsList/getDepositsList.js
  src/apis/depositsList/searchDepositsList.js
  src/pages/account/AccountDetail.jsx
  src/pages/account/AccountInquiryCard.jsx
  src/pages/deposits/DepositsList.jsx
  yarn.lock
Labels: Feat🐯

#89 상속 자산 조회 페이지 제작 및 API 연결
  package-lock.json
  package.json
  src/App.jsx
  src/apis/inheritance/getChartData.js
  src/apis/inheritance/getMyProperty.js
  src/apis/transfer/autoTransfer.js
  src/apis/transfer/simpleTransfer.js
  src/components/inheritance/card.jsx
  src/pages/inheritance/Inheritance.jsx
  src/pages/inheritance/component/Contract.jsx
  src/pages/inheritance/component/Property.jsx
  src/pages/transfer/AutoTransfer.jsx
  src/pages/transfer/SimpleTransfer.jsx
  src/pages/transfer/TransferView.jsx
  src/pages/transfer/component/Bankbtn.jsx
  src/pages/transfer/component/TransferAmount.jsx
  src/styles/globals.css
  src/styles/transaction.css
  yarn.lock
Labels: Feat🐯, 유언대용신탁, ⚡️api

#88 상속 홈화면 제작
  package-lock.json
  package.json
  public/favicon.ico
  public/images/senior01.jpeg
  src/App.jsx
  src/assets/mp4/heritage.mp4
  src/components/Layout.jsx
  src/pages/inheritance/InheritanceJoin.jsx
  src/pages/inheritance/component/Property.jsx
  src/styles/globals.css
  src/utils/utils.js
  yarn.lock
Labels: Feat🐯

#93 OCR페이지 제작
  src/App.jsx
  src/pages/inheritance/Inheritance.jsx
  src/pages/inheritance/OcrAuthentication.jsx
Labels: Feat🐯, ⚡️api

#97 유언 대용 신탁 계약 내용 조회 페이지 제작 및 정산페이지 axios 연결
  src/apis/admin/calculateSettlement.js
  src/apis/inheritance/getContractDetail.js
  src/components/common/Chart/BarChart.jsx
  src/pages/admin/Settlement.jsx
  src/pages/inheritance/component/Contract.jsx
  yarn.lock
Labels: Feat🐯

#100 내비게이션바 선택된 메뉴 스타일 적용 로직 추가
  src/Nav.js
  yarn.lock
Labels: Style🐰, 공통

#111 FaceId 화면 제작 및 기타 기능 수정
  package-lock.json
  package.json
  src/apis/inheritance/getContractDetail.js
  src/components/common/FaceId/PicComponent.jsx
  src/hooks/useAuth.js
  src/pages/account/AccountCreation3.jsx
  src/pages/deposits/DepositsJoin2.jsx
  src/pages/deposits/DepositsJoin3.jsx
  src/pages/inheritance/InheritanceJoin2.jsx
  src/pages/inheritance/OcrAuthentication.jsx
  src/pages/inheritance/component/Contract.jsx
  src/pages/inheritance/component/Property.jsx
  src/pages/user/Login.jsx
  yarn.lock
Labels: Feat🐯

#114 차트데이터 API 연동 수정
  package-lock.json
  src/components/inheritance/card.jsx
  src/pages/inheritance/component/Property.jsx
  yarn.lock
Labels: Chore🐷, 유언대용신탁
