Repository hee-ha/hana-heritage-FE, pull requests merged in 2024-05, with the labels that each got.

#6 Feat/#5 공통프레임작업
  package-lock.json
  package.json
  src/assets/fonts/NotoSans-Bold.ttf
  src/assets/fonts/NotoSans-Medium.ttf
  src/assets/fonts/NotoSans-Regular.ttf
  src/assets/fonts/NotoSansLao-Bold.ttf
  src/assets/fonts/NotoSansLao-Medium.ttf
  src/assets/fonts/NotoSansLao-Regular.ttf
  src/components/common/Button/Button.jsx
  src/pages/home/Home.jsx
  src/pages/login/Login.jsx
  src/styles/globals.css
  tailwind.config.js
Labels: Feat

#13 적금 상품 상세화면, 약관동의 화면 개발 (#3)
  package-lock.json
  package.json
  src/App.jsx
  src/pages/deposit/DepositDetail.jsx
  src/pages/deposit/DepositSign1.jsx
  src/pages/index.js
Labels: Feat

#17 feat:예적금상품_조회_페이지_제작(#10)
  src/pages/deposit/Deposit.jsx
  src/pages/deposit/Depositdetail.jsx
  src/pages/saving/Saving.jsx
  src/pages/saving/Savingdetail.jsx
Labels: Feat

#16 계좌이체 자동이체 페이지 화면 개발
  .idea/workspace.xml
  src/App.jsx
  src/Nav.js
  src/components/Header.jsx
  src/pages/index.js
  src/pages/simple-transaction/AutoTransfer.jsx
  src/pages/simple-transaction/SimpleTransaction.jsx
  src/pages/simple-transaction/TransferView.jsx
  src/pages/simple-transaction/component/Bankbtn.jsx
  src/pages/simple-transaction/component/TransferAmount.jsx
  src/styles/transaction.css
Labels: Feat

#15 feat : 예적금 가입 폼, 정보 확인, 가입 확정 페이지 구현
  src/App.jsx
  src/pages/saving/Confirmation.jsx
  src/pages/saving/Joinsuccess.jsx
  src/pages/saving/Saving2.jsx
Labels: Feat

#26 예적금상품 리스트 조회, 예적금 계좌 정보 조회 CSS 수정
  src/pages/account/AccountDetail.jsx
  src/pages/deposits/DepositsList.jsx
Labels: Style🐰

#25 거래내역페이지 CSS 수정
  src/pages/transfer/TransferHistory.jsx
Labels: Style🐰

#22 로그인, 회원가입, 계좌조회 스타일 수정
  src/pages/account/AccountInquiry.jsx
  src/pages/account/AccountInquiryCard.jsx
  src/pages/user/Identify.jsx
  src/pages/user/Login.jsx
  src/pages/user/Register.jsx
  src/pages/user/RegisterForm.jsx
Labels: Style🐰

#23 계좌이체 및 자동이체 화면 CSS 수정
  package-lock.json
  package.json
  src/App.jsx
  src/pages/deposits/DepositsDetail.jsx
  src/pages/deposits/DepositsJoin1.jsx
  src/pages/transfer/AutoTransfer.jsx
  src/pages/transfer/SimpleTransfer.jsx
  src/pages/transfer/TransferHome.jsx
  src/pages/transfer/TransferView.jsx
  src/pages/transfer/component/Bankbtn.jsx
Labels: Style🐰

#28 예적금 가입2, 예적금 가입3, 예적금 가입4 디자인 수정
  src/pages/deposits/DepositsJoin2.jsx
  src/pages/deposits/DepositsJoin3.jsx
  src/pages/deposits/DepositsJoin4.jsx
Labels: Style🐰

#45 Header, Nav 변경, prettier설정 변경
  .github/ISSUE_TEMPLATE/❗️feature.md
  .github/ISSUE_TEMPLATE/🐞-bug.md
  .github/pull_request_template.md
  .prettierrc
  package-lock.json
  package.json
  public/index.html
  src/App.jsx
  src/App.test.js
  src/Nav.js
  src/components/Dropdown/Dropdown.jsx
  src/components/Header.jsx
  src/components/common/Button/Button.jsx
  src/components/common/route/ScrollToTop.jsx
  src/index.js
  src/pages/deposits/DepositsJoin2.jsx
  src/pages/deposits/DepositsJoin3.jsx
  src/pages/deposits/DepositsList.jsx
  src/pages/index.js
  src/reportWebVitals.js
  src/setupTests.js
Labels: Chore🐷, Style🐰
